version: "3.9"

services:
  gpt-pdf-summariser:
    image: gpt-pdf-summarizer
    container_name: gpt-pdf-summarizer
    ports:
      - "127.0.0.1:8001:8001"
      - "127.0.0.1:8501:8501"
    volumes:
      - ./app:/app/app
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
